# Generated by Django 4.2.16 on 2024-11-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0002_furnitureitem_condition_furnitureitem_rental_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnitureitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='furniture/'),
        ),
    ]
