# Generated by Django 4.2.16 on 2024-11-24 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('furniture', '0003_furnitureitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnitureitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='furnitureitem',
            name='seller',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='furnitureitem',
            name='available_for_rent',
            field=models.BooleanField(default='Not Available For Rent'),
        ),
        migrations.AlterField(
            model_name='furnitureitem',
            name='available_for_sale',
            field=models.BooleanField(default='Available For Sale'),
        ),
    ]
