# Generated by Django 4.2.16 on 2024-11-24 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('furniture', '0004_furnitureitem_quantity_furnitureitem_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furnitureitem',
            name='seller',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
